[project]
name = "digicamify"
version = "1.0.0"
description = "Ensoulify your digital images."
dependencies = [
    "flask",
    "pillow",
    "numpy",
    "pillow_lut"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
